# export GITHUB_TOKEN=<>

# Snapshot
# goreleaser --snapshot --rm-dist

# Release
# git tag -a v0.1.0 -m "First release"
# git push origin v0.1.0
# goreleaser release

# Make sure to check the documentation at http://goreleaser.com

before:
  hooks:
    # you may remove this if you don't use vgo
    #- go mod tidy
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
- binary: "terraform-provider-k8s_v{{ .Version }}"
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
archives:
- files:
  - none*
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
